name: Merge to Master
on:
  push:
    branches:
      - master

jobs:
  main:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master

      - run: npm ci
        name: Install dependencies

      - run: npx nx affected -t build  --configuration production
        name: Build (production)
