name: Pushed to Repo
on:
  push:

jobs:
  main:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master

      - run: npm ci
        name: Install dependencies

      - run: npx nx affected -t lint --parallel=3
        name: Lint

      - run: npx nx affected -t test --parallel=3
        name: Test

      - run: npx nx affected -t build --parallel=3
        name: Build

      - run: npx nx affected -t e2e
        name: E2E Tests
